SELECT
    *
FROM
(
    SELECT
        'SKU PD' INDICADOR,
        SUB.APELIDO AS REPRESENTANTE,
        SUM(SEQUENCIA) AS OBJETIVO,
        AVG(SEQUENCIA) AS REALIZADO,
        '  R$ 200,00' 'BÔNUS PREVISTO',
        CASE
            WHEN AVG(SEQUENCIA) >= 12 THEN 200  
            ELSE 0
        END AS 'BÔNUS LIBERADO'
    FROM
        (
        SELECT
            VEN.APELIDO,
            COUNT(ITE.SEQUENCIA) AS SEQUENCIA
        FROM
            SANKHYA.TGFCAB CAB
            INNER JOIN SANKHYA.TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
            INNER JOIN SANKHYA.TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
            INNER JOIN SANKHYA.TGFTOP TPO ON ((TPO.CODTIPOPER = CAB.CODTIPOPER) AND TPO.DHALTER = CAB.DHTIPOPER)
            INNER JOIN SANKHYA.TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
            INNER JOIN SANKHYA.TGFVEN VEN ON (VEN.CODVEND = CAB.CODVEND)
        WHERE
            CAB.DTNEG BETWEEN CONVERT(DATE, '01/05/2024', 103) AND CONVERT(DATE, '30/05/2024', 103)
            AND CAB.STATUSNOTA = 'L'
            AND CAB.TIPMOV IN ('V', 'D')
            AND TPO.GOLSINAL = -1
            AND CAB.CODEMP IN (1, 40)
          
            --AND (@AUTH_OPERADOR_ID= VEN.CODVEND  OR @AUTH_REPRESENTANTE_ID = VEN.CODVEND)
          
        GROUP BY
            PAR.RAZAOSOCIAL,
            VEN.APELIDO,
            CAB.NUMNOTA
        ) AS SUB
    GROUP BY
        SUB.APELIDO
    UNION ALL
    SELECT
        'POSITIVAÇÃO' INDICADOR,
        APELIDO AS REPRESENTANTE,
        ROUND((META.QTDTOT * 0.8), 0) AS OBJETIVO,
        COUNT(DISTINCT (CAB.CODPARC)) REALIZADO,
        '  R$ 300,00' 'BÔNUS PREVISTO',
        CASE
            WHEN COUNT(DISTINCT (CAB.CODPARC)) >= ROUND((META.QTDTOT * 0.8), 0) THEN 300 
            ELSE '0'
        END 'BÔNUS LIBERADO'
    FROM
        SANKHYA.TGFCAB CAB
        INNER JOIN SANKHYA.TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
        INNER JOIN SANKHYA.TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
        INNER JOIN SANKHYA.TGFTOP TPO ON ((TPO.CODTIPOPER = CAB.CODTIPOPER) AND TPO.DHALTER = CAB.DHTIPOPER)
        INNER JOIN SANKHYA.TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
        INNER JOIN SANKHYA.TGFVEN VEN ON (VEN.CODVEND = CAB.CODVEND)
        LEFT JOIN SANKHYA.AD_METAVENDEDOR META ON (VEN.CODVEND = META.CODVEND AND IDMETA = 27)
    WHERE
        CAB.DTNEG BETWEEN CONVERT(DATE, '01/05/2024', 103) AND CONVERT(DATE, '31/05/2024', 103)
        AND CAB.STATUSNOTA = 'L'
        AND CAB.TIPMOV IN ('V', 'D')
        AND TPO.GOLSINAL = -1
        AND CAB.CODEMP IN (1, 40)
        
        --AND (@AUTH_OPERADOR_ID= VEN.CODVEND  OR @AUTH_REPRESENTANTE_ID = VEN.CODVEND)
        
          
    GROUP BY
        VEN.APELIDO,
        META.QTDTOT
    HAVING
        ISNULL((META.QTDTOT * 0.8), 0) <> 0
    UNION ALL
    SELECT
        'FATURAMENTO' INDICADOR,
        SUB.REPRESENTANTE,
        ROUND(SUM(SUB.META_BASF + SUB.META_KRONA + SUB.META_MIX), 2) AS OBJETIVO,
        ROUND(SUM(SUB.VALOR_BASF + SUB.VALOR_KRONA + SUB.VALOR_MIX), 2) AS REALIZADO,
        '  R$ 500,00' 'BONUS PREVISTO',
        CASE
            WHEN ROUND(SUM(SUB.VALOR_BASF + SUB.VALOR_KRONA + SUB.VALOR_MIX), 2) >= ROUND(SUM(SUB.META_BASF + SUB.META_KRONA + SUB.META_MIX), 2) THEN
             500
            ELSE '0'
        END 'BONUS LIBERADO'
    FROM
        (
        SELECT
        VEN.APELIDO AS REPRESENTANTE,
        ROUND(SUM(
            CASE
                WHEN PRO.CODPARCFORN IN (28008, 27828) THEN (((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * TPO.GOLDEV)
                ELSE 0
            END
        ), 2) AS VALOR_BASF,
        (SELECT VLRTOT FROM SANKHYA.AD_METAVENDEDOR METAA WHERE METAA.IDMETA = 14 AND METAA.DTREF = CONVERT(DATE, '01/05/2024', 103) AND METAA.CODVEND = VEN.CODVEND) AS META_BASF,
        ROUND(SUM(
            CASE
                WHEN PRO.CODPARCFORN = 819 THEN (((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * TPO.GOLDEV)
                ELSE 0
            END
        ), 2) AS VALOR_KRONA,
        (SELECT VLRTOT FROM SANKHYA.AD_METAVENDEDOR METAA WHERE METAA.IDMETA = 18 AND METAA.DTREF = CONVERT(DATE, '01/05/2024', 103) AND METAA.CODVEND = VEN.CODVEND) AS META_KRONA,
        ROUND(SUM(
            CASE
                WHEN PRO.CODPARCFORN NOT IN (819, 28008, 27828) THEN (((ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED + ITE.VLRSUBST + ITE.VLRIPI) * VCA.INDITENS) * TPO.GOLDEV)
                ELSE 0
            END
        ), 2) AS VALOR_MIX,
        (SELECT PREVREC FROM SANKHYA.TGFMET META WHERE META.DTREF = CONVERT(DATE, '01/05/2024', 103) AND META.CODVEND = VEN.CODVEND) AS META_MIX
        FROM
            SANKHYA.TGFCAB CAB
            INNER JOIN SANKHYA.TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
            INNER JOIN SANKHYA.TGFPRO PRO ON (PRO.CODPROD = ITE.CODPROD)
            RIGHT JOIN SANKHYA.VGFCAB VCA ON (VCA.NUNOTA = CAB.NUNOTA)
            INNER JOIN SANKHYA.TGFTOP TPO ON ((TPO.CODTIPOPER = CAB.CODTIPOPER) AND TPO.DHALTER = CAB.DHTIPOPER)
            INNER JOIN SANKHYA.TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
            INNER JOIN SANKHYA.TGFVEN VEN ON (VEN.CODVEND = CAB.CODVEND)
        WHERE
            CAB.DTNEG BETWEEN CONVERT(DATE, '01/05/2024', 103) AND CONVERT(DATE, '31/05/2024', 103)
            AND CAB.STATUSNOTA = 'L'
            AND CAB.TIPMOV IN ('V', 'D')
            AND TPO.GOLSINAL = -1
            AND CAB.CODEMP IN (1, 40)
          
          
           -- AND (@AUTH_OPERADOR_ID= VEN.CODVEND  OR @AUTH_REPRESENTANTE_ID = VEN.CODVEND)
          
          
        GROUP BY
            VEN.APELIDO,
            VEN.CODVEND
    ) SUB
    GROUP BY  SUB.REPRESENTANTE
    HAVING
        ROUND(SUM(SUB.META_BASF + SUB.META_KRONA + SUB.META_MIX), 2) IS NOT NULL
) K1